sudo: required
services:
  - docker

before_install:
  - docker build -t charliesd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run charliesd/react-test npm test -- --coverage

after_success:
  - docker build -t charliesd/multi-client ./client
  - docker build -t charliesd/multi-nginx ./nginx
  - docker build -t charliesd/multi-server ./server
  - docker build -t charliesd/multi-worker ./worker