sudo: required
services:
  - docker

before_install:
  - docker build -t charliesd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run charliesd/react-test npm test -- --coverage

after_success:
  - docker build -t charliesd/multi-client ./client
  - docker build -t charliesd/multi-nginx ./nginx
  - docker build -t charliesd/multi-server ./server
  - docker build -t charliesd/multi-worker ./worker
  
  # Log in to the docker CLI
  - echo "\$DOCKER_PASSWORD" | docker login -u "\$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push charliesd/multi-client
  - docker push charliesd/multi-nginx
  - docker push charliesd/multi-server
  - docker push charliesd/multi-worker

